name: MineQuest-RPG
main: com.theminequest.MQCoreRPG.MQCoreRPG
version: ${build.number}

author: JMonk
authors: [Echobob, Xu_R, Ltan, Makraiz, Blaksmith]

description: This plugin, and its add-ons expands Minecraft to add in Npcs, Quests, and custom events to create a Role-Play enviorment in Minecraft
website: www.theminequest.com

load: POSTWORLD

depend: [MineQuest]

commands:
   player:
      aliases: [mqplayer]
      description: Player Command for MineQuest
      usage: /<command>
      permission: minequest.rpg

permissions:
  minequest.rpg:
    description: Allows RPG commands
    default: true