name: MineQuest-RPG
main: com.theminequest.MQCoreRPG.MQCoreRPG
version: ${build.number}

author: JMonk
authors: [Echobob, Xu_R, Ltan, Makraiz, Blaksmith]

description: This plugin, and its add-ons expands Minecraft to add in Npcs, Quests, and custom events to create a Role-Play enviorment in Minecraft
website: www.theminequest.com

load: POSTWORLD

depend: [MineQuest]
softdepend: [Spout]

commands:
   player:
      aliases: [mqplayer]
      description: Player Command for MineQuest
      usage: /<command>
      permission: minequest.rpg
   stop:
      aliases: [mqstop]
      description: Stop the server by kicking everyone first.
      usage: /<command>
      permission: minequest.stop

permissions:
  minequest.rpg:
    description: Allows RPG commands
    default: true
  minequest.stop:
    description: Stop the server
    default: op